#!/usr/bin/env python3
"""Generate every builder page and every builder grid from data/builders.json.

    python3 tools/build-builders.py          # write
    python3 tools/build-builders.py --check  # fail if output is stale (CI)

⛔ NOTHING ON A BUILDER PAGE IS HAND-WRITTEN. Before 2026-09-21 these pages
carried floor plans no builder ever supplied -- "The Vista, 4 Beds, 3.5 Baths,
Up to 3,600 sq ft", invented three times over. Ranee, on seeing the site back:
"the changes that I asked for weren't made exactly... this has completely
changed, and that's completely changed." Copy that has an author cannot be
invented by an agent, so it lives in a data file with her asset-guide field
names on it, and a missing field renders as a marker that NAMES what is
missing rather than as prose.

⛔ EDIT THE JSON, NEVER THE HTML. Hand edits to find-a-home/builder-*.html are
overwritten on the next run, and --check fails the build if they are still
there.
"""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import panorama_site as S

DATA = json.loads((ROOT / "data" / "builders.json").read_text())
BUILDERS = DATA["builders"]

BANNER = "<!-- GENERATED by tools/build-builders.py from data/builders.json. Do not edit by hand. -->"
G_OPEN, G_CLOSE = "<!-- BUILDER-GRID:START -->", "<!-- BUILDER-GRID:END -->"


def pending(what):
    """A gap that says what it is. Never a sentence pretending to be copy."""
    return f'<p class="asset-pending-line"><span class="pending-tag">Pending</span> {what}</p>'


def poss(name):
    """Toll Brothers\u2019 website, not Toll Brothers\u2019s website."""
    return name + ("&rsquo;" if name.endswith("s") else "&rsquo;s")


def link_out(b):
    """The only CTA on the page. Ranee: no tours, no lead gen -- the whole job
    of a builder page is to hand the visitor to the builder."""
    if not b.get("url"):
        return (
            '<span class="btn btn-gold btn-disabled" aria-disabled="true">Builder website coming soon</span>'
            + pending(f"builder website URL for {b['name']}")
        )
    href = b["url"] + (b["utm"] or "")
    return (
        f'<a href="{href}" class="btn btn-gold" target="_blank" rel="noopener">'
        f'Visit {poss(b["name"])} website</a>'
    )


def gallery(b):
    """Ranee asked for 1-5 exterior and 1-5 interior images, as a click-through.
    ⛔ The slides are <img> in the markup, not JS-injected: the whole reason
    this pass exists is a page that paints blank until script runs."""
    shots = [("Exterior", p) for p in b["exteriorImages"]] + [
        ("Interior", p) for p in b["interiorImages"]
    ]
    if not shots:
        return (
            '<div class="builder-gallery is-empty">'
            + pending(f"1&ndash;5 exterior and 1&ndash;5 interior photos for {b['name']}")
            + "</div>"
        )
    slides = "".join(
        f'<figure class="builder-slide"><img src="../{p}" alt="{kind} &mdash; {b["name"]} at Panorama" loading="lazy"><figcaption>{kind}</figcaption></figure>'
        for kind, p in shots
    )
    dots = "".join(
        f'<button class="builder-dot" type="button" data-i="{i}" aria-label="Photo {i + 1} of {len(shots)}"></button>'
        for i in range(len(shots))
    )
    return (
        f'<div class="builder-gallery" data-count="{len(shots)}">'
        f'<div class="builder-track">{slides}</div>'
        f'<div class="builder-dots">{dots}</div></div>'
    )


def prose(text, what):
    if not text:
        return pending(what)
    return "".join(f"<p>{para}</p>" for para in text)


def bullets(items, what):
    if not items:
        return pending(what)
    return '<ul class="builder-diffs">' + "".join(f"<li>{i}</li>" for i in items) + "</ul>"


def models(b):
    if not b["modelHomes"]:
        # Ranee: addresses are "so that we can at least say what the addresses
        # are for the model homes WHEN THEY COME AVAILABLE." Not yet is the
        # expected state, so it is stated rather than hidden.
        return pending(f"model home address(es) for {b['name']} &mdash; expected once models open")
    return '<ul class="builder-models">' + "".join(f"<li>{m}</li>" for m in b["modelHomes"]) + "</ul>"


def logo_block(b, depth):
    if not b.get("logo"):
        return (
            '<div class="builder-logo-img placeholder"><span class="pending-tag">Logo pending</span></div>'
        )
    return f'<div class="builder-logo-img"><img src="{"../" * depth}{b["logo"]}" alt="{b["name"]}"></div>'


def page(b):
    d = 1
    title = f"{b['name']} at Panorama | Herriman"
    desc = (
        f"{b['name']} builds at Panorama, Herriman's foothills community. "
        f"See their homes and visit the builder's website."
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <meta name="description" content="{desc}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300;400;500;600&family=Inter:wght@300;400;500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../css/interior.css">
{S.head_guard(d)}
</head>
<body>
{BANNER}
{S.nav_html(d)}

  <section class="interior-hero interior-hero-plain">
    <div class="interior-hero-content">
      <div class="breadcrumb"><a href="../">Home</a> / <a href="../find-a-home/builders.html">Panorama Builders</a> / {b['name']}</div>
      {logo_block(b, d)}
      <h1>{b['name']}</h1>
      {f'<p class="builder-product">{b["productType"]}</p>' if b.get("productType") else ''}
    </div>
  </section>

  <section class="section section-dark">
    <div class="container builder-body">
      <div class="builder-intro">
        {prose([b['intro']] if b['intro'] else None, f"50-word introduction to {b['name']}")}
      </div>

      {gallery(b)}

      <h2>Homes by {b['name']} at Panorama</h2>
      {prose(b['homes'], f"2&ndash;4 paragraphs (~150 words) on the homes {b['name']} is building at Panorama")}

      <h2>What sets {b['name']} apart</h2>
      {bullets(b['differentiators'], f"4&ndash;8 differentiator bullets from {b['name']}")}

      <h2>Model homes</h2>
      {models(b)}
    </div>
  </section>

  <section class="cta-section">
    <div class="container">
      <h2>See everything {b['name']} offers</h2>
      <p>Availability, plans and pricing all live on the builder&rsquo;s own site.</p>
      {link_out(b)}
      <div style="margin-top:1rem;"><a href="../find-a-home/builders.html" class="btn btn-outline">Back to all builders</a></div>
    </div>
  </section>

{S.footer_html(d)}
  <script src="../js/builder-gallery.js" defer></script>
  <script>function toggleMobileMenu(){{document.getElementById('navLinks').classList.toggle('active');}}</script>
</body>
</html>
"""


def grid(depth):
    """The clickable logo wall. Ranee: 'all the builders and we'll do a little
    logo there or whatever, and then they can click onto their page.'"""
    up = "../" * depth
    cards = []
    for b in BUILDERS:
        logo = (
            f'<span class="builder-logo-img"><img src="{up}{b["logo"]}" alt="{b["name"]}"></span>'
            if b.get("logo")
            else f'<span class="builder-logo-img placeholder"><span class="pending-tag">Logo pending</span></span>'
        )
        meta = f'<span class="builder-meta">{b["productType"]}</span>' if b.get("productType") else ""
        cards.append(
            f'<a href="{up}find-a-home/builder-{b["slug"]}.html" class="builder-logo-link">'
            f'{logo}<span class="builder-name">{b["name"]}</span>{meta}'
            f'<span class="view-plans">View homes &rarr;</span></a>'
        )
    return (
        f'{G_OPEN}\n      <div class="builder-logo-grid">\n        '
        + "\n        ".join(cards)
        + f"\n      </div>\n      {G_CLOSE}"
    )


def splice(path, depth):
    """Replace whatever is between the grid markers. Returns (changed, text)."""
    p = ROOT / path
    t = p.read_text()
    if G_OPEN not in t or G_CLOSE not in t:
        return None, t
    head, rest = t.split(G_OPEN, 1)
    _, tail = rest.split(G_CLOSE, 1)
    new = head + grid(depth) + tail
    return new != t, new


def main():
    check = "--check" in sys.argv
    stale = []

    for b in BUILDERS:
        p = ROOT / "find-a-home" / f"builder-{b['slug']}.html"
        want = page(b)
        if not p.exists() or p.read_text() != want:
            stale.append(str(p.relative_to(ROOT)))
            if not check:
                p.write_text(want)

    for path, depth in (
        ("index.html", 0),
        ("find-a-home/index.html", 1),
        ("find-a-home/builders.html", 1),
    ):
        changed, new = splice(path, depth)
        if changed is None:
            print(f"  ! {path}: no BUILDER-GRID markers - grid not managed there")
            continue
        if changed:
            stale.append(path)
            if not check:
                (ROOT / path).write_text(new)

    if check:
        if stale:
            print("STALE - run `python3 tools/build-builders.py`:")
            for s in stale:
                print("   ", s)
            return 1
        print(f"builder output is current ({len(BUILDERS)} builders)")
        return 0

    print(f"wrote {len(BUILDERS)} builder pages + grids")
    for s in stale:
        print("   ", s)
    return 0


if __name__ == "__main__":
    sys.exit(main())
